-- 코드를 입력하세요
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE,ANIMAL_INS.NAME  FROM ANIMAL_INS 
JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE SEX_UPON_INTAKE != SEX_UPON_OUTCOME
ORDER BY ANIMAL_INS.ANIMAL_ID ASC