-- 코드를 입력하세요
# SELCET COUNT(USER_INFO.USER_ID) FROM USER_INFO WHERE JOINED LIKE '2021%'
# 구매한 사람수 / 전체 사람 수 전체 수 따로 구해보기

SELECT 
    DATE_FORMAT(O.SALES_DATE,'%Y') AS YEAR,    
    DATE_FORMAT(O.SALES_DATE,'%c') AS MONTH,
    COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS,
    ROUND((COUNT(DISTINCT U.USER_ID)) / (SELECT COUNT(USER_INFO.USER_ID) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) AS PUCHASED_RATIO
FROM USER_INFO AS U
INNER JOIN ONLINE_SALE AS O
ON U.USER_ID = O.USER_ID
WHERE U.JOINED LIKE '2021-%'
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, DATE_FORMAT(O.SALES_DATE,'%m') ASC